// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQuc2OxporEJNSNi75SvVb6L5J2SLiVHI',
    appId: '1:158155559721:web:719b5f021b1392e0e1dd38',
    messagingSenderId: '158155559721',
    projectId: 'uas-android-ac555',
    authDomain: 'uas-android-ac555.firebaseapp.com',
    storageBucket: 'uas-android-ac555.appspot.com',
    measurementId: 'G-HQDQZH10K8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDeSaOYnoRTcOLklRJtlQ51Rwj1D_EMpi4',
    appId: '1:158155559721:android:a6962d936abcbd14e1dd38',
    messagingSenderId: '158155559721',
    projectId: 'uas-android-ac555',
    storageBucket: 'uas-android-ac555.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBj3uI48roPIZLBjR-izLeozuDgwd8BwrQ',
    appId: '1:158155559721:ios:b8f886ae75b134e8e1dd38',
    messagingSenderId: '158155559721',
    projectId: 'uas-android-ac555',
    storageBucket: 'uas-android-ac555.appspot.com',
    iosClientId: '158155559721-qppkheclic31fm6vmhp8thuohng4ji21.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecanteen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBj3uI48roPIZLBjR-izLeozuDgwd8BwrQ',
    appId: '1:158155559721:ios:b8f886ae75b134e8e1dd38',
    messagingSenderId: '158155559721',
    projectId: 'uas-android-ac555',
    storageBucket: 'uas-android-ac555.appspot.com',
    iosClientId: '158155559721-qppkheclic31fm6vmhp8thuohng4ji21.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecanteen',
  );
}
